{% set version = "2.1-10" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gss
  version: {{ version|replace("-", "_") }}

source:
  fn: gss_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gss_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gss/gss_{{ version }}.tar.gz
  sha256: 26c47ecae6a9b7854a1b531c09f869cf8b813462bd8093e3618e1091ace61ee2

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('gss')"  # [not win]
    - "\"%R%\" -e \"library('gss')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gss
  license: GPL (>= 2)
  summary: A comprehensive package for structural multivariate function estimation using smoothing
    splines.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
