{% set version = "2.2-10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gss
  version: {{ version|replace('-', '_') }}

source:
  url:
    - https://cran.r-project.org/src/contrib/gss_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gss/gss_{{ version }}.tar.gz
  sha256: 11c4c91caf162a4077b2c2611cedfd7fbcfeae679f4438dcb7349c90aa2e7d07

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}              # [unix]
    - {{ stdlib('c') }}                # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}make
    - {{ posix }}coreutils             # [win]
    - {{ posix }}sed                   # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base

test:
  commands:
    - $R -e "library('gss')"  # [not win]
    - "\"%R%\" -e \"library('gss')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gss
  license: GPL-2.0-or-later
  summary: A comprehensive package for structural multivariate function estimation using smoothing splines.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
