travis:
  secure:
    BINSTAR_TOKEN: VmWO1VZwY6vtD6XBSf/DY5oofyxT7qktrfr+5GAi4uCvNi6DbWjeG8U3PVAO1wpF1uXKVTgehjsrm5zcYVPUlml5A4qkhkMHgZrGo33av/25WuRJJh3n5dLLRrSzRxOeiQvZvP+Ts1VjkRoqVf1QFyVKYDBfTdUmDEfbU+ha1eEF8Xnc1tG4bbE9EG7M2PY7MD6eD3dg+Fc86DaXedcx5ZPuq/lFyMKjOBWYaj/CwPos50C4KDNVqJIKGm1opDR7TPW6qLHk/nEmp65mCzwQAzPyEN7RVUHWdO2vN1cjjwUYeAsqQqVBwzoICkI39NnZTs6+AxZ2wKYJOoLHHuh5Khq+3psM9XpRZTJa3gzSjeAGw5Jo1dSggWmA2Mq8GC6Fxfyy1nUeJgUcZPCglXQRD9iOP2UpWoertG5qCplHe7o6jQXB8bcvYeBWP5tyIISx9o2paPGOWhDbJGydyZBkHuudkfJSeaZt9iNjl6xaWKnvcoZdafCNOy/Ni0Q6XqJHaK8M0EHnCTpPZybVH0dgBHY4FKWFv/19VQOYvAI44H/5J0gwEh4etWWFqnSGosDQ1Wl5WbikWBRE98dJxp6BaoKmQcu4YAapLFmRYhKu7k4k0P+LQI6LCaQ2/4ZjmWwy0peHgPw/bG6AR4H3Da5eVdx1P8qchn8eJQ7aMzcvSxA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
