appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ejAvPuAJjSGP1SoXvwCYWAAqD3B40YfUUX/XOwluA4xFqt61bL8jkgvAjgKuqNxGh2pWUHAKSXXgezE4/olgikXjMyexClIgInLfGH4TueCXuNLfxAM4q1cEhbPralKVuXKp7U9pSIzqj+S8FifhQ/xiHCpV8HKLslr3x5sfTn9MXtvE5FXt5jb3tq86gbYQeR9RJWRcbJXF1jfywrYZiT+g5Ma7Xa7JV/9YLmTHfEczYSE0Upi1eATFI9c3uYYJRXkowrreuA/6QRLcazLASuHXuMqXVyebSrX0h9lDSMV6sUNMHcJvFs7qqGYBEMrMofpwvhicUQSRlupJbTYcuHUZe1cIDRm+k+bQjk1FTeOLbpTNdbhK9c3nnJm5QosD2b3297+yaf32Dikfoxw9VTAbD7Fp2fYr6J22JKKqs4afO4OzGv+KmOeBD/kxZJKczsG+DJnixiOFl3I2PH47YGiCtvOL8dv+KfqFFb8Sol8OHAsBbHQ/g0/Ts7kxzEmYNOFVK7MNYFMM/jrdkRW3zfrPlSJT+MmrmP8QZRsBEoNyKg1I86RJL4YhBiOODduCtpLj5rpSH7IeV/gF/B3iQzlzsDhwx8EXscIrVaqMhbNkv0gsxh4ZoAItOYkTb0gltz2mdHI9r6SB6xXmltZ22ymbt+TwoOuz0C7/GVzqVBU=}
